### ISSUE TITLE
Grub files store in wrong directory (/usr/etc/grub.d/)

### ISSUE THREAD

**Issue by jcfrosty** [mocaccinoOS/mocaccino-musl-universe#81]
https://github.com/mocaccinoOS/mocaccino-musl-universe/blob/master/multi-arch/packages/grub/build.yaml#L28

build.yaml
   cd ${PACKAGE_NAME} && ./configure --prefix=/usr --target=$MUSL_TARGET --build=$MUSL_TARGET --host=$MUSL_TARGET \

grub files end up stored in /usr/etc/grub.d/ which is incorrect. Files need to stay in uniform location of /etc/grub.d/

**Comment by mudler** [comment]
That's package defaults, it is fine to have samples there. It's other package duties to have specifically conf files for the system setup

**Comment by geaaru** [comment]
It's better to have the path that is used in desktop too and in a lot of distro. This will permit to use `mos` in the same way without hardcoded changes for micro branch.
I think that is related to this:
https://github.com/gentoo/gentoo/blob/master/sys-boot/grub/grub-2.06.ebuild#L198
or without go to the link:
```
		--program-prefix=
		--libdir="${EPREFIX}/usr/lib
```

**Comment by jcfrosty** [comment]
I agree we should keep things uniform where possible. Not just for us when maintaining, but for end users and possible forks. Let's follow what Funtoo does.

**Comment by geaaru** [comment]
Done with d72121fa747ddea98740e3eed9830a76721cd7c0
